export const SET_TOURNAMENTS_LIST = 'SET_TOURNAMENTS_LIST';
export const SET_TOURNAMENT_INFO = 'SET_TOURNAMENT_INFO';
export const SET_TEAM_INFO = 'SET_TEAM_INFO';
export const ADD_FAVORITE_TEAM = 'ADD_FAVORITE_TEAM';
export const DELETE_FAVORITE_TEAM = 'DELETE_FAVORITE_TEAM';
export const ADD_FAVORITE_PLAYER = 'ADD_FAVORITE_PLAYER';
export const DELETE_FAVORITE_PLAYER = 'DELETE_FAVORITE_PLAYER';
export const TOGGLE_THEME = 'TOGGLE_THEME';
